const header=document.createElement("div");
header.setAttribute("class","header");
document.body.appendChild(header);
const titre=document.createElement("h1");
titre.textContent="Transfert D'agence";
header.appendChild(titre);
const form=document.createElement("form");
const divparent=document.createElement("div");
document.body.appendChild(divparent);
divparent.setAttribute("class","container");